# Generated by Django 2.2 on 2019-10-23 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_master',
            fields=[
                ('employee_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=25)),
                ('employee_contactno', models.BigIntegerField(default=0)),
                ('employee_unit', models.CharField(max_length=15)),
                ('employee_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_role', models.CharField(max_length=25)),
                ('employee_resaddr', models.CharField(max_length=250)),
                ('employee_joindate', models.DateField()),
                ('employee_remarks', models.TextField(max_length=250, null=True)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Product_master',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=250)),
                ('product_class', models.CharField(max_length=30)),
                ('product_specifications', models.TextField(max_length=250, null=True)),
                ('product_cost', models.IntegerField(default=0)),
                ('product_remarks', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('stage_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(default=0, max_length=100)),
                ('unit_location', models.CharField(default=0, max_length=250)),
                ('unit_employees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.Employee_master')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('machine_name', models.TextField(max_length=40)),
                ('machine_company', models.TextField(max_length=100)),
                ('machine_status', models.TextField(max_length=100)),
                ('machine_maintainer', models.TextField(max_length=300, null=True)),
                ('machine_remarks', models.TextField(max_length=250, null=True)),
                ('machine_handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.Employee_master')),
                ('machine_products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.Product_master')),
                ('machine_purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.Stages')),
                ('machine_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Company_master',
            fields=[
                ('company_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=40)),
                ('company_location', models.CharField(max_length=250)),
                ('company_billaddr', models.CharField(max_length=250)),
                ('company_deladdr', models.CharField(max_length=250)),
                ('company_website', models.URLField(null=True)),
                ('company_contactno', models.BigIntegerField(default=0)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_remarks', models.CharField(max_length=250, null=True)),
                ('company_products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.Product_master')),
            ],
        ),
    ]
