# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-18 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(upload_to=products.models._image_upload)),
                ('cropping', image_cropping.fields.ImageRatioField('image', '180x180', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('location', models.CharField(max_length=10, unique=True)),
                ('serial_number', models.CharField(max_length=40, unique=True)),
                ('quantity', models.IntegerField()),
                ('featured', models.IntegerField(choices=[(0, 'No'), (1, 'Everywhere'), (2, 'Category-only')], default=0)),
                ('categories', models.ManyToManyField(to='products.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set([('product', 'order')]),
        ),
    ]
