# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-19 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_placed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='discount_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='total_amount'),
        ),
    ]
