# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-14 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20191014_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={},
        ),
    ]
