# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20191014_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 - two character country code', max_length=2)),
                ('independence_day', models.DateField(blank=True, null=True)),
                ('area', models.BigIntegerField(blank=True, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Try and enter few some more lines')),
                ('architecture', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Continent'),
        ),
    ]
