# Generated by Django 2.2.1 on 2019-11-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryMaster',
            fields=[
                ('product_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category', models.CharField(max_length=50)),
            ],
        ),
    ]
